app_name = "c4web"
app_title = "C4 Web"
app_publisher = "Connect4systems"
app_description = "Modern Arabic RTL website for Connect4systems"
app_email = "info@connect4systems.com"
app_license = "MIT"

update_website_context = "c4web.utils.update_website_context"

modern_website_route_rules = [
    {"from_route": "/", "to_route": "index-modern"},
    {"from_route": "/home", "to_route": "index-modern"},
    {"from_route": "/index-ar", "to_route": "index-modern"},
    {"from_route": "/index-en", "to_route": "index-modern"},
    {"from_route": "/system", "to_route": "index-modern"},
    {"from_route": "/system2", "to_route": "index-modern"},
    {"from_route": "/sub", "to_route": "index-modern"},
    {"from_route": "/int", "to_route": "index-modern"},
    {"from_route": "/c4", "to_route": "index-modern"},
    {"from_route": "/connect", "to_route": "index-modern"},
    {"from_route": "/pages/PageEN", "to_route": "index-modern"},
    {"from_route": "/pages/PageAR", "to_route": "index-modern"},
    {"from_route": "/pages/my-page-6487", "to_route": "index-modern"},
    {"from_route": "/project/PageAR", "to_route": "index-modern"},
    {"from_route": "/rana", "to_route": "index-modern"},

    {"from_route": "/about", "to_route": "about-modern"},
    {"from_route": "/contact", "to_route": "contact-modern"},
    {"from_route": "/terms", "to_route": "terms-modern"},
    {"from_route": "/terms-and-conditions", "to_route": "terms-modern"},
    {"from_route": "/solution-template", "to_route": "solution-template-modern"},
    {"from_route": "/complete-solutions", "to_route": "complete-solutions-modern"},
    {"from_route": "/catalog", "to_route": "catalog-modern"},
    {"from_route": "/blog-list", "to_route": "blog-list-modern"},
    {"from_route": "/blog-post", "to_route": "blog-post-modern"},
    {"from_route": "/trade", "to_route": "trade-modern"},
    {"from_route": "/retail-system", "to_route": "retail-system-modern"},
    {"from_route": "/crm", "to_route": "crm-modern"},
    {"from_route": "/factory", "to_route": "factory-modern"},
    {"from_route": "/hr", "to_route": "hr-modern"},
    {"from_route": "/construction", "to_route": "construction-modern"},
    {"from_route": "/wells-solar", "to_route": "wells-solar-modern"},
    {"from_route": "/security-systems", "to_route": "security-systems-modern"},
    {"from_route": "/computer-networks", "to_route": "computer-networks-modern"},
    {"from_route": "/rent-app", "to_route": "rent-app-modern"},
    {"from_route": "/rental-companies", "to_route": "rental-companies-modern"},
    {"from_route": "/finance-management", "to_route": "finance-management-modern"},
    {"from_route": "/inventory-management", "to_route": "inventory-management-modern"},
    {"from_route": "/manufacturing-management", "to_route": "manufacturing-management-modern"},
    {"from_route": "/asset-management", "to_route": "asset-management-modern"},
    {"from_route": "/procurement-management", "to_route": "procurement-management-modern"},
    {"from_route": "/construction-management", "to_route": "construction-management-modern"},

    {"from_route": "/all-products", "to_route": "catalog-modern"},
    {"from_route": "/shop-by-category", "to_route": "catalog-modern"},
    {"from_route": "/%D8%A7%D9%84%D9%85%D9%86%D8%AA%D8%AC%D8%A7%D8%AA", "to_route": "catalog-modern"},
    {"from_route": "/e-commerce", "to_route": "catalog-modern"},
    {"from_route": "/retailtest", "to_route": "retail-system-modern"},
    {"from_route": "/retais-erp", "to_route": "retail-system-modern"},
    {"from_route": "/hr2", "to_route": "hr-modern"},
    {"from_route": "/stock", "to_route": "trade-modern"},
    {"from_route": "/sales", "to_route": "trade-modern"},
    {"from_route": "/ship", "to_route": "trade-modern"},
    {"from_route": "/Account_system", "to_route": "trade-modern"},
    {"from_route": "/web-development", "to_route": "solution-template-modern"},

    {"from_route": "/recruitment", "to_route": "hr-modern"},
    {"from_route": "/attendance", "to_route": "hr-modern"},
    {"from_route": "/leave-management", "to_route": "hr-modern"},
    {"from_route": "/expense-management", "to_route": "hr-modern"},
    {"from_route": "/performance-management", "to_route": "hr-modern"},
    {"from_route": "/salary-payouts", "to_route": "hr-modern"},
    {"from_route": "/tax-%26-benefits", "to_route": "hr-modern"},

    {"from_route": "/testabout", "to_route": "about-modern"},
    {"from_route": "/testregister", "to_route": "contact-modern"},
    {"from_route": "/test", "to_route": "contact-modern"},
    {"from_route": "/register", "to_route": "contact-modern"},
    {"from_route": "/cart", "to_route": "catalog-modern"},
    {"from_route": "/lms", "to_route": "blog-list-modern"},
    {"from_route": "/%D8%A7%D9%84%D8%AF%D8%B9%D8%AC", "to_route": "contact-modern"},

    {"from_route": "/blog/general-blog", "to_route": "blog-list-modern"},
    {"from_route": "/blog/partner", "to_route": "blog-list-modern"},
    {"from_route": "/blog/artical", "to_route": "blog-list-modern"},
    {"from_route": "/blog/erpnext", "to_route": "blog-list-modern"},
    {"from_route": "/blog/factories", "to_route": "blog-list-modern"},
    {"from_route": "/blog/real-state", "to_route": "blog-list-modern"},
    {"from_route": "/blog/hr", "to_route": "blog-list-modern"},
    {"from_route": "/blog/financial", "to_route": "blog-list-modern"},
    {"from_route": "/blog/stock", "to_route": "blog-list-modern"},
    {"from_route": "/blog/developer", "to_route": "blog-list-modern"},
    {"from_route": "/blog/%D9%85%D9%82%D8%A7%D9%84%D8%A7%D8%AA-%D8%B9%D8%A7%D9%85", "to_route": "blog-list-modern"},
    {"from_route": "/blog/%D8%A7%D9%84%D8%B4%D8%B1%D9%83%D8%A7%D8%AA-%D8%A7%D9%84%D8%AA%D8%AC%D8%A7%D8%B1%D9%8A%D8%A9", "to_route": "blog-list-modern"},
    {"from_route": "/blog/%D8%A7%D9%84%D9%85%D8%AD%D9%84%D8%A7%D8%AA", "to_route": "blog-list-modern"},
    {
        "from_route": "/blog/general-blog/p-style%3Dtext-align-right%3Bspan-style%3Dcolor-000000%3Bstrong%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D9%84%D8%B4%D8%B1%D9%83%D8%AA%D9%83-erp-system-%D9%83%D9%8A%D9%81%D9%8A%D8%A9-%D8%A7%D8%AE%D8%AA%D9%8A%D8%A7%D8%B1-strong-span-p",
        "to_route": "blog-post-modern",
    },
    {
        "from_route": "/blog/general-blog/h4-style%3Dtext-align-center%3Bspan-style%3Dcolor-000000%3Bstrong-%D9%88%D8%A3%D9%8A%D9%87%D9%85%D8%A7-%D8%A7%D9%84%D8%A3%D9%86%D8%B3%D8%A8-%D9%84%D8%B9%D9%85%D9%84%D9%83-erp%D9%88crm%D9%85%D8%A7-%D9%87%D9%88-%D8%A7%D9%84%D9%81%D8%B1%D9%82-%D8%A8%D9%8A%D9%86-strong-span-h4",
        "to_route": "blog-post-modern",
    },
    {
        "from_route": "/blog/erpnext/h2-style%3Dtext-align-right%3Bstrong%D9%84%D8%AA%D8%B7%D9%88%D9%8A%D8%B1-%D9%86%D8%B8%D8%A7%D9%85-%D8%A5%D8%AF%D8%A7%D8%B1%D8%A9-%D8%AC%D9%88%D8%AF%D8%A9-%D9%85%D8%B1%D9%86-%D8%AA%D8%B9%D8%B2%D9%8A%D8%B2-%D8%A7%D9%84%D9%85%D8%B1%D9%88%D9%86%D8%A9-%D9%88%D8%A7%D9%84%D9%83%D9%81%D8%A7%D8%A1%D8%A9-%D9%81%D9%8A-%D8%A7%D9%84%D8%AA%D8%B5%D9%86%D9%8A%D8%B9-erpnext-strong-h2",
        "to_route": "blog-post-modern",
    },
    {
        "from_route": "/blog/erpnext/app-versions-%60%60%60-%7B-builder-1123-ecommerce-integrations-1201-erpnext-15393-frappe-15451-hr-policy-",
        "to_route": "blog-post-modern",
    },
    {"from_route": "/blog/<path:slug>", "to_route": "blog-post-modern"},
    {"from_route": "/blog/trade1", "to_route": "blog-post-modern"},
]

legacy_website_route_rules = [
    {"from_route": "/home", "to_route": "index"},
    {"from_route": "/index-ar", "to_route": "index"},
    {"from_route": "/index-en", "to_route": "index"},
    {"from_route": "/system", "to_route": "index"},
    {"from_route": "/system2", "to_route": "index"},
    {"from_route": "/sub", "to_route": "index"},
    {"from_route": "/int", "to_route": "index"},
    {"from_route": "/c4", "to_route": "index"},
    {"from_route": "/connect", "to_route": "index"},
    {"from_route": "/pages/PageEN", "to_route": "index"},
    {"from_route": "/pages/PageAR", "to_route": "index"},
    {"from_route": "/pages/my-page-6487", "to_route": "index"},
    {"from_route": "/project/PageAR", "to_route": "index"},
    {"from_route": "/rana", "to_route": "index"},

    {"from_route": "/all-products", "to_route": "catalog"},
    {"from_route": "/shop-by-category", "to_route": "catalog"},
    {"from_route": "/%D8%A7%D9%84%D9%85%D9%86%D8%AA%D8%AC%D8%A7%D8%AA", "to_route": "catalog"},
    {"from_route": "/e-commerce", "to_route": "catalog"},

    {"from_route": "/trade", "to_route": "trade"},
    {"from_route": "/retail-system", "to_route": "retail-system"},
    {"from_route": "/factory", "to_route": "factory"},
    {"from_route": "/crm", "to_route": "crm"},
    {"from_route": "/hr", "to_route": "hr"},
    {"from_route": "/construction", "to_route": "construction"},
    {"from_route": "/wells-solar", "to_route": "wells-solar"},
    {"from_route": "/security-systems", "to_route": "security-systems"},
    {"from_route": "/computer-networks", "to_route": "computer-networks"},
    {"from_route": "/rent-app", "to_route": "rent-app"},
    {"from_route": "/rental-companies", "to_route": "rental-companies"},
    {"from_route": "/finance-management", "to_route": "finance-management"},
    {"from_route": "/inventory-management", "to_route": "inventory-management"},
    {"from_route": "/manufacturing-management", "to_route": "manufacturing-management"},
    {"from_route": "/asset-management", "to_route": "asset-management"},
    {"from_route": "/procurement-management", "to_route": "procurement-management"},
    {"from_route": "/construction-management", "to_route": "construction-management"},

    {"from_route": "/retailtest", "to_route": "retail-system"},
    {"from_route": "/retais-erp", "to_route": "retail-system"},
    {"from_route": "/hr2", "to_route": "hr"},
    {"from_route": "/stock", "to_route": "trade"},
    {"from_route": "/sales", "to_route": "trade"},
    {"from_route": "/ship", "to_route": "trade"},
    {"from_route": "/Account_system", "to_route": "trade"},
    {"from_route": "/web-development", "to_route": "solution-template"},
    {"from_route": "/complete-solutions", "to_route": "complete-solutions"},
    {"from_route": "/terms", "to_route": "terms"},
    {"from_route": "/terms-and-conditions", "to_route": "terms"},

    {"from_route": "/recruitment", "to_route": "hr"},
    {"from_route": "/attendance", "to_route": "hr"},
    {"from_route": "/leave-management", "to_route": "hr"},
    {"from_route": "/expense-management", "to_route": "hr"},
    {"from_route": "/performance-management", "to_route": "hr"},
    {"from_route": "/salary-payouts", "to_route": "hr"},
    {"from_route": "/tax-%26-benefits", "to_route": "hr"},

    {"from_route": "/testabout", "to_route": "about"},
    {"from_route": "/testregister", "to_route": "contact"},
    {"from_route": "/test", "to_route": "contact"},
    {"from_route": "/register", "to_route": "contact"},
    {"from_route": "/cart", "to_route": "catalog"},
    {"from_route": "/lms", "to_route": "blog-list"},
    {"from_route": "/%D8%A7%D9%84%D8%AF%D8%B9%D8%AC", "to_route": "contact"},

    {"from_route": "/blog/general-blog", "to_route": "blog-list"},
    {"from_route": "/blog/partner", "to_route": "blog-list"},
    {"from_route": "/blog/artical", "to_route": "blog-list"},
    {"from_route": "/blog/erpnext", "to_route": "blog-list"},
    {"from_route": "/blog/factories", "to_route": "blog-list"},
    {"from_route": "/blog/real-state", "to_route": "blog-list"},
    {"from_route": "/blog/hr", "to_route": "blog-list"},
    {"from_route": "/blog/financial", "to_route": "blog-list"},
    {"from_route": "/blog/stock", "to_route": "blog-list"},
    {"from_route": "/blog/developer", "to_route": "blog-list"},
    {"from_route": "/blog/%D9%85%D9%82%D8%A7%D9%84%D8%A7%D8%AA-%D8%B9%D8%A7%D9%85", "to_route": "blog-list"},
    {"from_route": "/blog/%D8%A7%D9%84%D8%B4%D8%B1%D9%83%D8%A7%D8%AA-%D8%A7%D9%84%D8%AA%D8%AC%D8%A7%D8%B1%D9%8A%D8%A9", "to_route": "blog-list"},
    {"from_route": "/blog/%D8%A7%D9%84%D9%85%D8%AD%D9%84%D8%A7%D8%AA", "to_route": "blog-list"},

    {
        "from_route": "/blog/general-blog/p-style%3Dtext-align-right%3Bspan-style%3Dcolor-000000%3Bstrong%D9%85%D9%86%D8%A7%D8%B3%D8%A8-%D9%84%D8%B4%D8%B1%D9%83%D8%AA%D9%83-erp-system-%D9%83%D9%8A%D9%81%D9%8A%D8%A9-%D8%A7%D8%AE%D8%AA%D9%8A%D8%A7%D8%B1-strong-span-p",
        "to_route": "blog-post",
    },
    {
        "from_route": "/blog/general-blog/h4-style%3Dtext-align-center%3Bspan-style%3Dcolor-000000%3Bstrong-%D9%88%D8%A3%D9%8A%D9%87%D9%85%D8%A7-%D8%A7%D9%84%D8%A3%D9%86%D8%B3%D8%A8-%D9%84%D8%B9%D9%85%D9%84%D9%83-erp%D9%88crm%D9%85%D8%A7-%D9%87%D9%88-%D8%A7%D9%84%D9%81%D8%B1%D9%82-%D8%A8%D9%8A%D9%86-strong-span-h4",
        "to_route": "blog-post",
    },
    {
        "from_route": "/blog/erpnext/h2-style%3Dtext-align-right%3Bstrong%D9%84%D8%AA%D8%B7%D9%88%D9%8A%D8%B1-%D9%86%D8%B8%D8%A7%D9%85-%D8%A5%D8%AF%D8%A7%D8%B1%D8%A9-%D8%AC%D9%88%D8%AF%D8%A9-%D9%85%D8%B1%D9%86-%D8%AA%D8%B9%D8%B2%D9%8A%D8%B2-%D8%A7%D9%84%D9%85%D8%B1%D9%88%D9%86%D8%A9-%D9%88%D8%A7%D9%84%D9%83%D9%81%D8%A7%D8%A1%D8%A9-%D9%81%D9%8A-%D8%A7%D9%84%D8%AA%D8%B5%D9%86%D9%8A%D8%B9-erpnext-strong-h2",
        "to_route": "blog-post",
    },
    {
        "from_route": "/blog/erpnext/app-versions-%60%60%60-%7B-builder-1123-ecommerce-integrations-1201-erpnext-15393-frappe-15451-hr-policy-",
        "to_route": "blog-post",
    },
    {"from_route": "/blog/<path:slug>", "to_route": "blog-post"},
    {"from_route": "/blog/trade1", "to_route": "blog-post"},
]

website_route_rules = modern_website_route_rules + legacy_website_route_rules
